#
# Settings used for development in Local Beach
#

Neos:
  Flow:
    persistence:
      backendOptions:
        host: '%env:BEACH_DATABASE_HOST%'
        dbname: '%env:BEACH_DATABASE_NAME%'
        user: '%env:BEACH_DATABASE_USERNAME%'
        password: '%env:BEACH_DATABASE_PASSWORD%'
        port: '%env:BEACH_DATABASE_PORT%'

  ContentRepository:
    Search:
      elasticSearch:
        indexName: '%env:BEACH_ELASTICSEARCH_INDEX_NAME%'

Flowpack:
  ElasticSearch:
    clients:
      default:
        - host: '%env:BEACH_ELASTICSEARCH_HOSTNAME%'
          port: '%env:BEACH_ELASTICSEARCH_PORT%'
          username: '%env:BEACH_ELASTICSEARCH_USERNAME%'
          password: '%env:BEACH_ELASTICSEARCH_PASSWORD%'
